---

- name: Install epel-release
  yum: name=epel-release state=present

- name: Install packages
  yum: name={{ item }} state=present
  with_items:
    - libselinux-python
    - redis

- name: Deploy redis configuration file
  template: src=redis.conf.j2 dest=/etc/redis.conf
  notify:
   - restart redis

- name: Set vm.overcommit_memory=1
  sysctl: name=vm.overcommit_memory value=1 state=present

- name: Ensure redis service is started and enabled
  service: name=redis state=started enabled=yes

- name: Ensure redis is up and running
  command: redis-cli ping
  register: redis_response

- name: assert redis is up
  fail: msg='redis is not happy'
  when: redis_response.stdout != "PONG"