---

- name: Get pepyatka-lite local version
  command: chdir=/var/www/pepyatka-lite git rev-parse HEAD
  register: pepyatka_lite_local_version
  tags:
    - pepyatka
    - nginx

- name: Fetch pepyatka-lite remote
  command: chdir=/var/www/pepyatka-lite git fetch origin
  tags:
    - pepyatka
    - nginx

- name: Get pepyatka-lite version on remote
  command: chdir=/var/www/pepyatka-lite git rev-parse origin/{{ pepyatka_lite_branch }}
  register: pepyatka_lite_remote_version
  tags:
    - pepyatka
    - nginx

- name: Update pepyatka-lite
  git:
    repo: "{{ pepyatka_lite_repo }}"
    update: yes
    dest: /var/www/pepyatka-lite
    version: "{{ pepyatka_lite_branch }}"
    force: yes
  register: pepyatka_lite
  when: pepyatka_lite_local_version.stdout != pepyatka_lite_remote_version.stdout
  tags:
    - pepyatka
    - nginx

- name: Save changelog in a file
  shell: echo "{{ pepyatka_lite_local_version.stdout }}...{{ pepyatka_lite_remote_version.stdout }}" > /tmp/pepyatka-lite-changelog
  when: pepyatka_lite_local_version.stdout != pepyatka_lite_remote_version.stdout
  tags: pepyatka

- name: Fetch pepyatka-lite changelog
  fetch:
    src=/tmp/pepyatka-lite-changelog
    dest=pepyatka-lite-changelog/{{ inventory_hostname }}
    flat=yes
  when: pepyatka_lite_local_version.stdout != pepyatka_lite_remote_version.stdout
  tags: pepyatka

- name: Deploy pepyatka-lite config
  template: src=pepyatka-lite-config.json.j2 dest=/var/www/pepyatka-lite/config.json
  tags:
    - pepyatka
    - nginx

- name: Sync standard images from pepyatka-html
  command: rsync -a --delete /var/www/pepyatka-html/public/img /var/www/pepyatka-lite
  tags:
    - pepyatka
    - nginx

- name: Fix pepyatka-lite permissions
  file:
    path: /var/www/pepyatka-lite
    owner: "{{ www_user }}"
    group: "{{ www_group }}"
    state: directory
    recurse: yes
  tags:
    - pepyatka
    - nginx
