- name: Deploy pepyatka-lite
  git:
    repo: "{{ pepyatka_lite_repo }}"
    update: yes
    dest: /var/www/pepyatka-lite
    version: "{{ pepyatka_lite_branch }}"
    force: yes
  register: pepyatka_lite
  tags:
    - pepyatka
    - nginx

- name: Save changelog in a file
  shell: echo "{{ pepyatka_lite.before }}...{{ pepyatka_lite.after }}" > /tmp/pepyatka-lite-changelog
  when: pepyatka_lite.before != pepyatka_lite.after
  tags: pepyatka

- name: Fetch pepyatka-lite changelog
  fetch:
    src=/tmp/pepyatka-lite-changelog
    dest=pepyatka-lite-changelog/{{ inventory_hostname }}
    flat=yes
  when: pepyatka_lite.before != pepyatka_lite.after
  tags: pepyatka

- name: Deploy pepyatka-lite config
  template: src=pepyatka-lite-config.json.j2 dest=/var/www/pepyatka-lite/config.json
  tags:
    - pepyatka
    - nginx

- name: Install webpack
  npm: path=/var/www/pepyatka-lite state=latest
  tags:
    - pepyatka
    - nginx

- name: Kill local node_modules
  file: path=/var/www/pepyatka-lite/node_modules state=absent
  when: pepyatka_lite.before != pepyatka_lite.after
  tags:
    - pepyatka
    - nginx

- name: Install pepyatka-lite dependencies
  npm: path=/var/www/pepyatka-lite state=latest
  tags:
    - pepyatka
    - nginx

- name: Build the bundle
  environment:
    ___BUILD___: "stable_{{ pepyatka_lite.after | truncate(8, True, '') }}"
  command: ./node_modules/.bin/webpack --config config.js
  args:
    chdir: /var/www/pepyatka-lite
  tags:
    - pepyatka
    - nginx

- name: Deploy md5 script
  copy: src=write_hash.sh dest=/var/www/pepyatka-lite/ mode=0755
  tags:
    - pepyatka
    - nginx

- name: Append md5 hashes to file urls
  command: chdir=/var/www/pepyatka-lite ./write_hash.sh
  tags:
    - pepyatka
    - nginx

- name: Update ga account
  replace:
    dest: /var/www/pepyatka-lite/config.json
    regexp: "UA-0-1"
    replace: "{{ pepyatka_ga_account }}"
  tags:
    - pepyatka
    - nginx

- name: Sync standard images from pepyatka-html
  command: rsync -a --delete /var/www/pepyatka-html/public/img /var/www/pepyatka-lite
  tags:
    - pepyatka
    - nginx

- name: Fix pepyatka-lite permissions
  file:
    path: /var/www/pepyatka-lite
    owner: "{{ www_user }}"
    group: "{{ www_group }}"
    state: directory
    recurse: yes
  tags:
    - pepyatka
    - nginx
