- name: Deploy freefeed-react-client
  git:
    repo: "{{ freefeed_react_client_repo }}"
    update: yes
    dest: /var/www/freefeed-react-client
    version: "{{ freefeed_react_client_branch }}"
    force: yes
  register: freefeed_react_client

- name: Save changelog in a file
  shell: echo "{{ freefeed_react_client.before }}...{{ freefeed_react_client.after }}" > /tmp/freefeed-react-client-changelog
  when: freefeed_react_client.before != freefeed_react_client.after

- name: Fetch freefeed-react-client changelog
  fetch:
    src=/tmp/freefeed-react-client-changelog
    dest=freefeed-react-client-changelog/{{ inventory_hostname }}
    flat=yes
  when: freefeed_react_client.before != freefeed_react_client.after

- name: Update service name in index.jade
  replace:
    dest: /var/www/freefeed-react-client/index.jade
    regexp: "Reactive Pepyatka"
    replace: "{{ pepyatka_service_name }}"

- name: Update api.host in src/config.js
  replace:
    dest: /var/www/freefeed-react-client/src/config.js
    regexp: "host:.*"
    replace: "host: '{{ pepyatka_frontend_scheme }}://{{ freefeed_react_client_hostname }}',"

- name: Update cookie domain in src/config.js
  replace:
    dest: /var/www/freefeed-react-client/src/config.js
    regexp: "cookieDomain.*"
    replace: "cookieDomain: '{{ pepyatka_auth_cookie_domain }}',"

- name: Update tokenPrefix in src/config.js
  replace:
    dest: /var/www/freefeed-react-client/src/config.js
    regexp: "tokenPrefix:.*"
    replace: "tokenPrefix: '{{ freefeed_auth_token_prefix }}',"

- name: Update whoAmI cache key in src/config.js
  replace:
    dest: /var/www/freefeed-react-client/src/config.js
    regexp: "userStorageKey.*"
    replace: "userStorageKey: '{{ pepyatka_local_storage_whoami_cache_key }}',"

- name: Update captcha.siteKey in src/config.js
  replace:
    dest: /var/www/freefeed-react-client/src/config.js
    regexp: "siteKey.*"
    replace: "siteKey: '{{ freefeed_recaptcha_sitekey }}',"

- name: Read bookmarklet.min.js from Ember client
  shell: cat /var/www/pepyatka-html/public/js/bookmarklet.min.js
  register: bookmarklet_min_js_content
  changed_when: false
  ignore_errors: yes

- name: Populate BOOKMARKLET_PLACEHOLDER
  replace:
    dest: /var/www/freefeed-react-client/src/components/sidebar.jsx
    regexp: "BOOKMARKLET_PLACEHOLDER"
    replace: "{{ bookmarklet_min_js_content.stdout }}"
  ignore_errors: yes

- name: Copy bookmarklet-popup.js from Ember client
  command: cp /var/www/pepyatka-html/public/js/bookmarklet-popup.js /var/www/freefeed-react-client/public/
  register: bookmarklet_popup_js
  changed_when: false
  ignore_errors: yes

- name: Replace host in bookmarklet-popup.js
  replace:
    dest: /var/www/freefeed-react-client/public/bookmarklet-popup.js
    regexp: "\+ host \+"
    replace: "+ {{ pepyatka_frontend_scheme }}://{{ pepyatka_html_hostname }} + "

- name: Install webpack globally
  npm: name=webpack state=latest global=yes

- name: Kill local node_modules
  file: path=/var/www/freefeed-react-client/node_modules state=absent
  when: freefeed_react_client.before != freefeed_react_client.after

- name: Install freefeed-react-client dependencies
  npm: path=/var/www/freefeed-react-client state=latest

- name: Build assets
  command: make prod out_dir=/var/www/freefeed-react-client/public
  args:
    chdir: /var/www/freefeed-react-client

- name: Fix freefeed-react-client permissions
  file:
    path: /var/www/freefeed-react-client
    owner: "{{ www_user }}"
    group: "{{ www_group }}"
    state: directory
    recurse: yes

