---

- name: Check if swap file exists
  stat: path="{{ swap_file }}"
  register: stat_swap_file

- name: Create swap file
  command: dd if=/dev/zero of="{{ swap_file }}" bs="{{ swap_bs }}" count="{{ swap_count }}"
  when: not stat_swap_file.stat.exists

- name: Set permissions on swap file
  file: path="{{ swap_file }}" mode=0600

- name: Format swap file
  command: mkswap "{{ swap_file }}"
  when: not stat_swap_file.stat.exists

- name: Add to fstab
  lineinfile:
    dest: /etc/fstab
    regexp: "{{ swap_file }}"
    line: "{{ swap_file }} none swap sw 0 0"

- name: Turn on swap
  command: swapon -a

- name: Set swapiness
  sysctl:
    name: vm.swappiness
    value: "1"
