---
- name: Install unattended upgrades package.
  apt: pkg=unattended-upgrades state=installed

- name: Copy unattended-upgrades configuration files in place.
  copy: >
    src="{{ item }}"
    dest=/etc/apt/apt.conf.d/
    owner=root group=root mode=0644
  with_items:
    - 10periodic
    - 50unattended-upgrades