---

pepyatka_html_repo: https://github.com/pepyatka/pepyatka-html.git
pepyatka_html_branch: development
www_user: www-data
www_group: www-data
pepyatka_hostname: localhost
pepyatka_server_host: localhost
pepyatka_server_port: 3000
pepyatka_frontend_scheme: http
pepyatka_files_dir: /var/pepyatka-files
nginx_client_max_body_size: '10M'
nginx_use_proxy_protocol: False
pepyatka_ga_account: "UA-XXXXXX"
