---

- name: Ensure database is created
  become: yes
  become_user: postgres
  postgresql_db: name={{ crypto_private_db_name }}

- name: Ensure user has access to database
  become: yes
  become_user: postgres
  postgresql_user:
    db={{ crypto_private_db_name }}
    name={{ crypto_private_db_user }}
    password={{ crypto_private_db_pass }}
    priv=ALL

- name: Ensure user does not have unnecessary privilege
  become: yes
  become_user: postgres
  postgresql_user: name={{ crypto_private_db_user }} role_attr_flags=NOSUPERUSER,NOCREATEDB

- name: Deploy db schema
  template: src=schema.sql.j2 dest=/tmp/schema.sql

- name: Deploy .pgpass
  template: src=pgpqss.j2 dest=/root/.pgpass mode=0600

- name: Init db schema
  command: psql -U {{ crypto_private_db_user }} -d {{ crypto_private_db_name }} -h {{ crypto_private_db_host }} -f /tmp/schema.sql
