---

- name: Check which env is active
  become: yes
  docker_container_info:
    name: nginx-blue
  register: result

- set_fact:
    old_env: green
    new_env: blue
    old_port: 8081
    new_port: 8080
  when: not result.container

- set_fact:
    old_env: blue
    new_env: green
    old_port: 8080
    new_port: 8081
  when: result.container

- name: Ensure /etc/freefeed
  become: yes
  file:
    path: /etc/freefeed
    state: directory

- set_fact:
    server_containers: []

- set_fact:
    server_containers: "{{ server_containers + ['freefeed-server-'+item] }}"
  with_sequence: count="{{ freefeed_server_instances }}"

- name: Render nginx config
  become: yes
  template: src="{{ item }}.j2" dest="/etc/freefeed/{{ item }}"
  loop:
    - nginx.conf
    - freefeed-common.conf
  register: nginx_conf

- name: Pull images
  become: yes
  docker_image:
    name: "{{ item }}"
    source: pull
    state: present
    force_source: yes
  loop:
    - "{{ react_client_image }}"
    - "{{ vanilla_image }}"
    - "nginx:latest"
  register: pull_images

- name: Create freefeed-react-client container
  become: yes
  docker_container:
    name: "freefeed-react-client-{{ new_env }}"
    image: "{{ react_client_image }}"
    command: echo
    state: present

- name: Create vanilla container
  become: yes
  docker_container:
    name: "vanilla-{{ new_env }}"
    image: "{{ vanilla_image }}"
    command: echo
    state: present

- name: Start nginx container
  become: yes
  docker_container:
    name: "nginx-{{ new_env }}"
    image: nginx:latest
    volumes_from:
      - "freefeed-react-client-{{ new_env }}"
      - "vanilla-{{ new_env }}"
    published_ports:
      - "{{ new_port }}:80"
    volumes:
      - /etc/freefeed/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/freefeed/freefeed-common.conf:/etc/nginx/freefeed-common.conf:ro
    networks:
      - name: freefeed
    state: started
    restart_policy: on-failure

- name: Switch port in nginx.conf
  become: yes
  lineinfile:
    path: /etc/nginx/nginx.conf
    regexp: "server localhost:{{ old_port }};$"
    line: "      server localhost:{{ new_port }};"

- name: Reload nginx
  systemd:
    name: nginx
    state: reloaded

- pause:
    seconds: 5

- name: Delete old containers
  become: yes
  docker_container:
    name: "{{ item }}"
    state: absent
    force_kill: yes
  loop:
    - "nginx-{{ old_env }}"
    - "freefeed-react-client-{{ old_env }}"
    - "vanilla-{{ old_env }}"

