---

- name: Import pganalyze collector pgp key
  become: yes
  apt_key: url=https://packages.pganalyze.com/pganalyze_signing_key.asc state=present

- name: Add pganalyze collector repo
  become: yes
  apt_repository: repo='deb https://packages.pganalyze.com/debian/stretch/ stable main' state=present

- name: Install packages
  become: yes
  apt: name="{{ item }}" state=present update_cache=yes
  with_items:
    - pganalyze-collector

- name: Deploy pganalyze-collector config
  become: yes
  template: src=pganalyze-collector.conf.j2 dest=/etc/pganalyze-collector.conf

