---

- fail: msg="Pepyatka server is only supported for Ubuntu"
  when: ansible_distribution != 'Ubuntu'

- name: Add the myway apt repository
  apt_repository: repo="ppa:dhor/myway" state=present
  tags:
    - graphicsmagick
    - pepyatka

- name: Install GraphicsMagick
  apt: name=graphicsmagick state=present update-cache=yes
  tags:
    - graphicsmagick
    - pepyatka

- name: Create pepyatka user
  user:
    name: "{{ pepyatka_user }}"
    home: "{{ pepyatka_home_dir }}"
    createhome: yes
    system: yes
  tags: pepyatka

- name: Ensure git is installed
  apt: name=git state=present

- name: Deploy pepyatka-server
  sudo: yes
  sudo_user: "{{ pepyatka_user }}"
  git:
    repo: "{{ pepyatka_server_repo }}"
    update: yes
    dest: "{{ pepyatka_home_dir }}/pepyatka-server"
    version: "{{ pepyatka_version }}"
    force: yes
  notify:
    - restart pepyatka
  tags: pepyatka

- name: Fix server name in development.js
  sudo: yes
  sudo_user: "{{ pepyatka_user }}"
  replace:
    dest: "{{ pepyatka_home_dir }}/pepyatka-server/config/environments/development.js"
    regexp: "http://localhost:3333"
    replace: "{{ fe_hostname }}"
  notify: restart pepyatka
  tags: pepyatka

- name: Patch redis connect options in config/database.js
  sudo: yes
  sudo_user: "{{ pepyatka_user }}"
  replace:
    dest: "{{ pepyatka_home_dir }}/pepyatka-server/config/database.js"
    regexp: 'database = redis\.createClient\(\)'
    replace: 'database = redis.createClient({{ pepyatka_redis_port }}, "{{ pepyatka_redis_host }}", {})'
  notify: restart pepyatka
  tags: pepyatka

- name: Patch redis connect options in pubsub.js - 1
  sudo: yes
  sudo_user: "{{ pepyatka_user }}"
  replace:
    dest: "{{ pepyatka_home_dir }}/pepyatka-server/app/pubsub.js"
    regexp: 'redis\(\)'
    replace: 'redis({{ pepyatka_redis_port }}, "{{ pepyatka_redis_host }}", {})'
  notify: restart pepyatka
  tags: pepyatka

- name: Patch redis connect options in pubsub.js - 2
  sudo: yes
  sudo_user: "{{ pepyatka_user }}"
  replace:
    dest: "{{ pepyatka_home_dir }}/pepyatka-server/app/pubsub.js"
    regexp: 'redis\({ detect_buffers: true }\)'
    replace: 'redis({{ pepyatka_redis_port }}, "{{ pepyatka_redis_host }}", { detect_buffers: true })'
  notify: restart pepyatka
  tags: pepyatka

- name: Install pepyatka-server dependencies
  sudo: yes
  sudo_user: "{{ pepyatka_user }}"
  npm: path="{{ pepyatka_home_dir }}/pepyatka-server"
  tags: pepyatka

- name: Install pm2
  npm: name=pm2 global=yes state=latest
  tags: pepyatka

- name: Init pm2
  command: "pm2 startup ubuntu -u {{ pepyatka_user }}"
  tags: pepyatka

- name: Get list of Node.js apps running
  sudo: yes
  sudo_user: "{{ pepyatka_user }}"
  command: pm2 list
  register: pm2_list
  changed_when: false
  tags: pepyatka

- name: Start pepyatka-server
  sudo: yes
  sudo_user: "{{ pepyatka_user }}"
  environment:
    NODE_ENV: development
  command: chdir="{{ pepyatka_home_dir }}" pm2 start --name pepyatka pepyatka-server/index.js
  when: "pm2_list.stdout.find('pepyatka') == -1"
  tags: pepyatka

- name: Ensure pepyatka is up and running
  wait_for: host=localhost port=3000 timeout=30 state=started
  tags:
    - nginx
