---

- fail: msg="Pepyatka server is only supported for Ubuntu"
  when: ansible_distribution != 'Ubuntu'

- name: Add the myway apt repository
  apt_repository: repo="ppa:dhor/myway" state=present
  tags:
    - graphicsmagick
    - pepyatka

- name: Install GraphicsMagick
  apt: name=graphicsmagick state=present update-cache=yes
  tags:
    - graphicsmagick
    - pepyatka

- name: Create pepyatka user
  user:
    name: "{{ pepyatka_user }}"
    home: "{{ pepyatka_home_dir }}"
    createhome: yes
    system: yes
  tags: pepyatka

- name: Install required packages
  apt: name={{ item }} state=present
  with_items:
    - git
    - make
    - g++
  tags: pepyatka

- name: Deploy pepyatka-server
  sudo: yes
  sudo_user: "{{ pepyatka_user }}"
  git:
    repo: "{{ pepyatka_server_repo }}"
    update: yes
    dest: "{{ pepyatka_home_dir }}/pepyatka-server"
    version: "{{ pepyatka_server_version }}"
    force: yes
  notify:
    - restart pepyatka
  tags: pepyatka

- name: Deploy pepaytka config
  template:
    src: environment.js.j2
    dest: "{{ pepyatka_home_dir }}/pepyatka-server/config/environments/{{ pepyatka_node_env }}.js"
    owner: "{{ pepyatka_user }}"
    group: "{{ pepyatka_group }}"
  notify:
    - restart pepyatka
  tags: pepyatka

- name: Create directories for attachments and thumbnails
  file:
    path: "{{ pepyatka_files_dir }}/{{ item }}"
    state: directory
    owner: "{{ pepyatka_user }}"
  with_items:
    - original
    - thumbnails
  tags:
    - pepyatka

- name: Install pepyatka-server dependencies
  sudo: yes
  sudo_user: "{{ pepyatka_user }}"
  npm: path="{{ pepyatka_home_dir }}/pepyatka-server"
  tags: pepyatka

- name: Install pm2
  npm: name=pm2 global=yes state=latest
  tags: pepyatka

- name: Init pm2
  command: "pm2 startup ubuntu -u {{ pepyatka_user }}"
  tags: pepyatka

- name: Get list of Node.js apps running
  sudo: yes
  sudo_user: "{{ pepyatka_user }}"
  command: pm2 list
  register: pm2_list
  changed_when: false
  tags: pepyatka

- name: Start pepyatka-server
  sudo: yes
  sudo_user: "{{ pepyatka_user }}"
  command: chdir="{{ pepyatka_home_dir }}" pm2 start --name pepyatka pepyatka-server/index.js NODE_ENV={{ pepyatka_node_env }}
  when: "pm2_list.stdout.find('pepyatka') == -1"
  tags: pepyatka

- name: Ensure pepyatka is up and running
  wait_for: host=localhost port={{ pepyatka_server_port }} timeout=30 state=started
  tags:
    - nginx
