---

- fail: msg="Pepyatka server is only supported for Ubuntu"
  when: ansible_distribution != 'Ubuntu'

- name: Add the myway apt repository
  apt_repository: repo="ppa:dhor/myway" state=present
  tags:
    - graphicsmagick
    - pepyatka

- name: Install GraphicsMagick
  apt: name=graphicsmagick state=present update-cache=yes
  tags:
    - graphicsmagick
    - pepyatka

- name: Create pepyatka user
  user:
    name: "{{ pepyatka_user }}"
    home: "{{ pepyatka_home_dir }}"
    createhome: yes
    system: yes
  tags:
    - pepyatka

- name: Clone pepyatka-server
  local_action: git repo="{{ pepyatka_server_repo }}" update=yes dest=pepyatka-server version="{{ pepyatka_version }}"
  tags:
    - pepyatka

- name: Deploy pepyatka-server
  synchronize:
    src: pepyatka-server
    dest: "{{ pepyatka_home_dir }}/"
    recursive: yes
    mode: push
    delete: yes
    rsync_opts: --no-motd,--exclude=.git
  notify:
    - restart pepyatka
  tags:
    - pepyatka

- name: Fix server name in development.js
  replace:
    dest: "{{ pepyatka_home_dir }}/pepyatka-server/config/environments/development.js"
    regexp: "http://localhost:3333"
    replace: "https://{{ fe_hostname }}"
  notify:
    - restart pepyatka
  tags:
    - pepyatka

- name: Install pepyatka-server dependencies
  npm: path="{{ pepyatka_home_dir }}/pepyatka-server"
  tags:
    - pepyatka

- name: Fix pepyatka-server permissions
  file:
    path: "{{ pepyatka_home_dir }}/pepyatka-server"
    owner: "{{ pepyatka_user }}"
    group: "{{ pepyatka_group }}"
    state: directory
    recurse: yes
  tags:
    - pepyatka

- name: Install pm2
  npm: name=pm2 global=yes state=latest
  tags:
    - pepyatka

- name: Init pm2
  command: "pm2 startup ubuntu -u {{ pepyatka_user }}"
  tags:
    - pepyatka

- name: Get list of Node.js apps running
  su: yes
  su_user: "{{ pepyatka_user }}"
  command: pm2 list
  register: pm2_list
  changed_when: false
  tags:
    - pepyatka

- name: Start pepyatka-server
  su: yes
  su_user: "{{ pepyatka_user }}"
  command: chdir="{{ pepyatka_home_dir }}" pm2 start pepyatka-server/index.js -i 0 --name pepyatka
  when: "pm2_list.stdout.find('pepyatka') == -1"
  tags:
    - pepyatka

