---
- name: restart sshd
  service: name=sshd state=restarted

- name: set SELinux permissions
  shell: restorecon -v /etc/ssh/ssh*_config; restorecon -rv /root/.ssh
  ignore_errors: True
  changed_when: False
