---

- name: Install git
  yum: name=git state=present

- name: Deploy pepyatka-server.git
  git: repo={{ pepyatka_server_repo }} dest={{ pepyatka_server_dir }} accept_hostkey=True

- name: Deploy conf/envLocal.js
  template: src=envLocal.js.j2 dest={{ pepyatka_server_dir }}/conf/envLocal.js

- name: Install dependencies
  npm: path={{ pepyatka_server_dir }}

- name: "Install forever"
  npm: name=forever global=yes state=latest

- name: "Check list of Node.js apps running."
  command: forever list
  register: forever_list
  changed_when: false

- name: "Start pepyatka-server"
  environment:
    NODE_ENV: production
  command: chdir={{ pepyatka_server_dir }} forever start index.js
  when: "forever_list.stdout.find('{{ pepyatka_server_dir }}/index.js') == -1"
