---

www_user: www-data
www_group: www-data

react_client_dir: /var/www/freefeed-react-client
react_client_repo: https://github.com/freefeed/freefeed-react-client.git
react_client_branch: stable
react_client_hostname: "{{ inventory_hostname }}"

local_storage_whoami_cache_key: whoamiCache
auth_token_prefix: dummy_
recaptcha_client_secret: ""
public_sentry_dsn: 'https://0123456789abcdef0123456789abcdef@app.getsentry.com/12345'
frontend_scheme: http
reg_limit_form_iframe_src: ""
