---

- name: Download Oracle JDK RPM
  command: 'wget -q --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" "{{ jdk_download_url }}" -O "{{ jdk_download_path }}/{{ jdk_rpm_name }}"'
  args:
    creates: "{{ jdk_download_path }}/{{ jdk_rpm_name }}"
  tags:
    - java

- name: Install Oracle JDK
  yum: name="{{ jdk_download_path }}/{{ jdk_rpm_name }}" state=present
  tags:
    - java

- name: Deploy elasticsearch-1.4.repo
  copy: src=elasticsearch-1.4.repo dest=/etc/yum.repos.d/

- name: Download and install the Public Signing Key for elasticsearch
  rpm_key: key="https://packages.elasticsearch.org/GPG-KEY-elasticsearch" state=present

- name: Install packages
  yum: name={{ item }} state=present
  with_items:
    - elasticsearch
    - python-pip

