---

- name: Install python-software-properties
  apt: pkg=python-software-properties update-cache=yes state=latest
  tags:
    - java

- name: Add the webupd8 APT repository
  apt_repository: repo="ppa:webupd8team/java" state=present
  tags:
    - java

- name: Automatically select the Oracle License
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
  changed_when: false
  tags:
    - java

- name: Install Oracle Java
  apt: pkg=oracle-java8-installer update-cache=yes state=latest
  tags:
    - java

- name: Download and install the Public Signing Key for elasticsearch
  apt_key: url="https://packages.elasticsearch.org/GPG-KEY-elasticsearch" state=present

- name: Add the elasticsearch APT repository
  apt_repository: repo="deb http://packages.elasticsearch.org/elasticsearch/1.5/debian stable main" state=present

- name: Install packages
  apt: name={{ item }} state=present update-cache=yes
  with_items:
    - elasticsearch
    - python-pip

