- name: Add gpg key for the docker repository
  become: yes
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add docker apt repository
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present

- name: Update cache
  become: yes
  apt:
    update_cache: yes

- name: Install docker packages
  become: yes
  apt:
    name: docker-ce,docker-ce-cli,containerd.io,python-docker

- name: Ensure python docker module is installed
  become: yes
  pip: name=docker state=present

