---

- pre_tasks:
  hosts: all
  connection: local
  gather_facts: False
  become: False
  tasks:
    - name: Delete saved changelogs
      file: path={{ item }} state=absent
      with_items:
        - pepyatka-server-changelog
        - pepyatka-html-changelog
        - pepyatka-lite-changelog
        - crypto-private-changelog
      when: slack_token is defined
      tags:
        - changelog

    - name: Send notification to Slack
      local_action:
        module: slack
        token: "{{ slack_token }}"
        msg: "Starting deploy to <{{ pepyatka_frontend_scheme }}://{{ pepyatka_hostname }}|{{ pepyatka_hostname }}>"

- include: elasticsearch.yml
- include: redis.yml
- include: postgres.yml
- include: pepyatka.yml
- include: cryptoprivate.yml
- include: nginx.yml

- post_tasks:
  hosts: all
  connection: local
  gather_facts: False
  become: False
  tasks:
    - name: Send pepyatka-server changelog to Slack
      local_action:
        module: slack
        token: "{{ slack_token }}"
        msg: "Updated pepyatka-server on {{ item | basename }}. <{{ pepyatka_server_repo | replace('.git', '')}}/compare/{{ lookup('file', item) }}|Changelog>"
      with_fileglob:
        - pepyatka-server-changelog/*
      when: slack_token is defined
      tags:
        - changelog

    - name: Send pepyatka-html changelog to Slack
      local_action:
        module: slack
        token: "{{ slack_token }}"
        msg: "Updated pepyatka-html on {{ item | basename }}. <{{ pepyatka_html_repo | replace('.git', '')}}/compare/{{ lookup('file', item) }}|Changelog>"
      with_fileglob:
        - pepyatka-html-changelog/*
      when: slack_token is defined
      tags:
        - changelog

    - name: Send pepyatka-lite changelog to Slack
      local_action:
        module: slack
        token: "{{ slack_token }}"
        msg: "Updated pepyatka-lite on {{ item | basename }}. <{{ pepyatka_lite_repo | replace('.git', '')}}/compare/{{ lookup('file', item) }}|Changelog>"
      with_fileglob:
        - pepyatka-lite-changelog/*
      when: slack_token is defined
      tags:
        - changelog

    - name: Send crypto-private changelog to Slack
      local_action:
        module: slack
        token: "{{ slack_token }}"
        msg: "Updated crypto-private on {{ item | basename }}. <{{ crypto_private_repo | replace('.git', '')}}/compare/{{ lookup('file', item) }}|Changelog>"
      with_fileglob:
        - crypto-private-changelog/*
      when: slack_token is defined
      tags:
        - changelog

    - name: Send notification to Slack
      local_action:
        module: slack
        token: "{{ slack_token }}"
        msg: "Successfully deployed <{{ pepyatka_frontend_scheme }}://{{ pepyatka_hostname }}|{{ pepyatka_hostname }}>"

