---

- pre_tasks:
  hosts: all
  connection: local
  gather_facts: False
  sudo: False
  vars:
    slack_pre_data: 'payload={"text": "Starting deploy to <{{ pepyatka_frontend_scheme }}://{{ pepyatka_hostname }}|{{ pepyatka_hostname }}>"}'
  tasks:
    - name: Delete saved changelogs
      file: path={{ item }} state=absent
      with_items:
        - pepyatka-server-changelog
        - pepyatka-html-changelog
        - pepyatka-lite-changelog
        - crypto-private-changelog
      when: slack_notification_url is defined
      tags:
        - changelog

    - include: slack.yml message="{{ slack_pre_data }}"

- include: elasticsearch.yml
- include: redis.yml
- include: postgres.yml
- include: pepyatka.yml
- include: cryptoprivate.yml
- include: nginx.yml

- post_tasks:
  hosts: all
  connection: local
  gather_facts: False
  sudo: False
  vars:
    slack_post_data: 'payload={"text": "Successfully deployed <{{ pepyatka_frontend_scheme }}://{{ pepyatka_hostname }}|{{ pepyatka_hostname }}>"}'
  tasks:
    - name: Generate pepyatka-server changelog message for Slack
      shell: echo "Updated pepyatka-server on {{ item | basename }}. <{{ pepyatka_server_repo | replace('.git', '')}}/compare/{{ lookup('file', item) }}|Changelog>"
      with_fileglob:
        - pepyatka-server-changelog/*
      register: pepyatka_server_changelog
      when: slack_notification_url is defined
      tags:
        - changelog

    - include: slack.yml message="{{ item.stdout }}"
      with_items: pepyatka_server_changelog.results
      when: pepyatka_server_changelog.changed

    - name: Generate pepyatka-html changelog message for Slack
      shell: echo "Updated pepyatka-html on {{ item | basename }}. <{{ pepyatka_html_repo | replace('.git', '')}}/compare/{{ lookup('file', item) }}|Changelog>"
      with_fileglob:
        - pepyatka-html-changelog/*
      register: pepyatka_html_changelog
      when: slack_notification_url is defined
      tags:
        - changelog

    - include: slack.yml message="{{ item.stdout }}"
      with_items: pepyatka_html_changelog.results
      when: pepyatka_html_changelog.changed

    - name: Generate pepyatka-lite changelog message for Slack
      shell: echo "Updated pepyatka-lite on {{ item | basename }}. <{{ pepyatka_lite_repo | replace('.git', '')}}/compare/{{ lookup('file', item) }}|Changelog>"
      with_fileglob:
        - pepyatka-lite-changelog/*
      register: pepyatka_lite_changelog
      when: slack_notification_url is defined
      tags:
        - changelog

    - include: slack.yml message="{{ item.stdout }}"
      with_items: pepyatka_lite_changelog.results
      when: pepyatka_lite_changelog.changed

    - name: Generate crypto-private changelog message for Slack
      shell: echo "Updated crypto-private on {{ item | basename }}. <{{ crypto_private_repo | replace('.git', '')}}/compare/{{ lookup('file', item) }}|Changelog>"
      with_fileglob:
        - crypto-private-changelog/*
      register: crypto_private_changelog
      when: slack_notification_url is defined
      tags:
        - changelog

    - include: slack.yml message="{{ item.stdout }}"
      with_items: crypto_private_changelog.results
      when: crypto_private_changelog.changed

    - include: slack.yml message="{{ slack_post_data }}"
      when: not pepyatka_server_changelog.changed
            and not pepyatka_html_changelog.changed
            and not pepyatka_lite_changelog.changed

