---

- pre_tasks:
  hosts: all
  connection: local
  gather_facts: False
  become: False
  tasks:
    - name: Delete saved changelogs
      file: path="playbooks/{{ item }}" state=absent
      with_items:
        - pepyatka-server-changelog
        - vanilla-changelog
        - react-client-changelog
      when: slack_token is defined
      tags:
        - changelog

- include: pepyatka.yml
- include: pepyatka-frontend.yml

- post_tasks:
  hosts: all
  connection: local
  gather_facts: False
  become: False
  tasks:
    - name: Send pepyatka-server changelog to Slack
      local_action:
        module: slack
        token: "{{ slack_token }}"
        msg: "Updated pepyatka-server on {{ item | basename }}. <{{ pepyatka_server_repo | replace('.git', '')}}/compare/{{ lookup('file', item) }}|Changelog>"
      with_fileglob:
        - pepyatka-server-changelog/*
      when: slack_token is defined
      tags:
        - changelog

    - name: Send react-client changelog to Slack
      local_action:
        module: slack
        token: "{{ slack_token }}"
        msg: "Updated react-client on {{ item | basename }}. <{{ react_client_repo | replace('.git', '')}}/compare/{{ lookup('file', item) }}|Changelog>"
      with_fileglob:
        - react-client-changelog/*
      when: slack_token is defined
      tags:
        - changelog

    - name: Send vanilla changelog to Slack
      local_action:
        module: slack
        token: "{{ slack_token }}"
        msg: "Updated vanilla on {{ item | basename }}. <{{ vanilla_repo | replace('.git', '')}}/compare/{{ lookup('file', item) }}|Changelog>"
      with_fileglob:
        - vanilla-changelog/*
      when: slack_token is defined and vanilla_enabled
      tags:
        - changelog

